name: Android CI - Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 4. Build APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TechCables-APK
          path: app/build/outputs/apk/debug/app-debug.apk
